name: VNC Server
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'

jobs:
  run-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          token: ${{ secrets.FINE_GRAINED_PAT }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'

      - name: Install packages
        run: |
          rm ~/.bashrc
          echo 'PS1="\\[\\e[38;5;39m\\]╭─\\[\\e[38;5;39m\\][\\[\\e[38;5;220m\\]server14\\[\\e[38;5;39m\\]@\\[\\e[38;5;83m\\]gamedreams.eu\\[\\e[38;5;39m\\]]─[\\[\\e[38;5;208m\\]\\w\\[\\e[38;5;39m\\]]\\n\\[\\e[38;5;39m\\]╰─\\[\\e[38;5;208m\\]λ\\[\\e[0m\\] "' > ~/.bashrc
          echo 'cd /home/runner' >> ~/.bashrc
          source ~/.bashrc
          
          sudo apt-get update
          sudo apt-get install -y fonts-dejavu-core xterm xarchiver feh htop openbox obconf tint2 xfce4-terminal pcmanfm tigervnc-standalone-server tigervnc-common neofetch falkon nano vim curl python3

          wget -O playit https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-linux-amd64
          mv playit /usr/local/bin/

          wget https://github.com/tmate-io/tmate/releases/download/2.4.0/tmate-2.4.0-static-linux-i386.tar.xz
          tar -xvf tmate-2.4.0-static-linux-i386.tar.xz
          mv tmate-2.4.0-static-linux-i386/tmate /usr/local/bin/
          rm -rf tmate-2.4.0-static-linux-i386*

          curl -fsSL https://raw.githubusercontent.com/filebrowser/get/master/get.sh | bash

      - name: Setup environment
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          mkdir -p ~/.vnc ~/.config/{pcmanfm/default,xfce4/terminal,tint2,openbox}
          echo '1234' | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd
          
          mkdir -p ~/Pictures
          curl https://i.imgur.com/s5KMeNv.png -o ~/Pictures/wallpaper.png
          
          echo '[*]
          wallpaper_mode=stretch
          wallpaper_common=1
          wallpaper=/home/runner/Pictures/wallpaper.png
          desktop_bg=#000000
          desktop_fg=#ffffff
          desktop_shadow=#000000
          desktop_font=Sans 12
          show_wm_menu=0
          sort=mtime;ascending;
          show_documents=0
          show_trash=1
          show_mounts=0' > ~/.config/pcmanfm/default/desktop-items-0.conf
          
          echo '[Configuration]
          FontName=DejaVu Sans Mono 12
          MiscDefaultGeometry=80x24' > ~/.config/xfce4/terminal/terminalrc
          
          echo 'background_color = #000000 100
          panel_items = LTSC
          panel_size = 100% 30
          panel_position = bottom center horizontal
          taskbar_name = 1
          taskbar_name_padding = 4
          taskbar_name_background_id = 0
          taskbar_name_font = sans 9
          taskbar_mode = single_desktop
          taskbar_padding = 0 0 2
          task_maximum_size = 150 30
          task_padding = 2 2
          launcher_padding = 2 2
          launcher_icon_size = 24
          launcher_item_app = org.kde.falkon.desktop
          launcher_item_app = xfce4-terminal.desktop
          launcher_item_app = pcmanfm.desktop' > ~/.config/tint2/tint2rc
          
          echo '#!/bin/bash
          xrdb $HOME/.Xresources
          xsetroot -solid grey
          export XKL_XMODMAP_DISABLE=1
          openbox-session &
          tint2 &
          pcmanfm --desktop &
          falkon --no-sandbox &
          xfce4-terminal &
          while true; do
             sleep 60
          done' > ~/.vnc/xstartup
          chmod +x ~/.vnc/xstartup
          
          echo '#!/bin/bash
          tint2 &
          pcmanfm --desktop &' > ~/.config/openbox/autostart
          chmod +x ~/.config/openbox/autostart
          
          filebrowser config init -d ~/.filebrowser.db
          filebrowser config set -d ~/.filebrowser.db --address 0.0.0.0
          filebrowser config set -d ~/.filebrowser.db --port 9090
          filebrowser config set -d ~/.filebrowser.db --root /
          filebrowser config set -d ~/.filebrowser.db --auth.method=noauth
          filebrowser users add runner 1234 --perm.admin -d ~/.filebrowser.db

      - name: Start services
        env:
          FINE_GRAINED_PAT: ${{ secrets.FINE_GRAINED_PAT }}
          REPO: ${{ github.repository }}
        run: |
          vncserver :1 -geometry 1280x800 -depth 24 -rfbport 7000
          filebrowser -d ~/.filebrowser.db &
          tmate -S /tmp/tmate.sock new-session -d "bash --noprofile"
          tmate -S /tmp/tmate.sock wait tmate-ready
          tmate -S /tmp/tmate.sock display -p "#{tmate_ssh}"
          playit start &
          
          START_TIME=$(date +%s)
          
          while true; do
            cd $GITHUB_WORKSPACE
            git add persist/
            git commit -m "Auto commit [no ci]" || true
            git push https://x-access-token:${FINE_GRAINED_PAT}@github.com/${REPO}.git HEAD:main --force || true
            
            CURRENT_TIME=$(date +%s)
            ELAPSED_TIME=$((CURRENT_TIME - START_TIME))
            
            if [ $ELAPSED_TIME -ge 18000 ]; then
              curl -X POST -H "Authorization: token $FINE_GRAINED_PAT" \
                -H "Accept: application/vnd.github.v3+json" \
                "https://api.github.com/repos/${REPO}/actions/workflows/vnc-server.yml/dispatches" \
                -d '{"ref":"main"}'
              exit 0
            fi
            
            sleep 1800
          done

      - name: Rerun workflow if failed
        if: failure()
        env:
          FINE_GRAINED_PAT: ${{ secrets.FINE_GRAINED_PAT }}
          REPO: ${{ github.repository }}
        run: |
          curl -X POST -H "Authorization: token $FINE_GRAINED_PAT" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${REPO}/actions/workflows/vnc-server.yml/dispatches" \
            -d '{"ref":"main"}'
